plot3=function(){
  data=read.table("./household_power_consumption.txt", header = TRUE, sep =";"  )
  subdata=subset(data, Date == "1/2/2007" | Date =="2/2/2007")
  timedate=strptime(paste(subdata$Date, subdata$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
  subdata=cbind(subdata, timedate)
  subdata$Sub_metering_1=as.numeric(subdata$Sub_metering_1)
  subdata$Sub_metering_2=as.numeric(subdata$Sub_metering_2)
  subdata$Sub_metering_3=as.numeric(subdata$Sub_metering_3)
  png("plot3.png", width=480, height=480)
  with(subdata, plot(timedate, Sub_metering_1, type="l", xlab="",ylab="Energy sub metering"))  
  with(subdata, lines(timedate, Sub_metering_2, type="l", col="red"))  
  with(subdata, lines(timedate, Sub_metering_3, type="l", col="blue"))  
  legend(c("topright"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty="solid",lwd=2, col = c("black", "red", "blue"))
  dev.off()
}